# Generated by Django 6.0.5 on 2026-05-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('ingestion_mode', models.CharField(choices=[('CSV_UPLOAD', 'CSV File Upload'), ('API_STUB', 'API Integration (stub)'), ('MANUAL', 'Manual Entry')], default='CSV_UPLOAD', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed')], default='PROCESSING', max_length=30)),
                ('total_rows', models.IntegerField(default=0)),
                ('accepted_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='ingestion.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_json', models.JSONField()),
                ('parse_status', models.CharField(choices=[('RAW', 'Raw (not yet processed)'), ('NORMALIZED', 'Successfully Normalized'), ('FAILED', 'Failed to Normalize')], default='RAW', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.importbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('source_record_id', models.CharField(blank=True, default='', help_text='Original record ID from source system (e.g. SAP document number)', max_length=100)),
                ('activity_type', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity_original', models.FloatField()),
                ('unit_original', models.CharField(max_length=50)),
                ('quantity_normalized', models.FloatField()),
                ('unit_normalized', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1 — Direct Emissions'), ('Scope 2', 'Scope 2 — Indirect (Electricity)'), ('Scope 3', 'Scope 3 — Value Chain')], max_length=10)),
                ('location_details', models.JSONField(blank=True, default=dict)),
                ('emission_factor_source', models.CharField(blank=True, default='', max_length=200)),
                ('estimated_emissions_kgco2e', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=10)),
                ('flags', models.JSONField(blank=True, default=list, help_text='List of flag strings, e.g. ["missing_plant", "zero_quantity"]')),
                ('review_status', models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked for Audit')], default='NEEDS_REVIEW', max_length=20)),
                ('analyst_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.importbatch')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='ingestion.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Record Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('EDITED', 'Edited'), ('LOCKED', 'Locked for Audit')], max_length=20)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('actor', models.CharField(default='analyst', help_text='Simplified actor field — production would use auth user', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.emissionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('tenant', 'source_type')},
        ),
    ]
